### PR TITLE
Don't reuse the already loaded repositories

### PR DESCRIPTION
**Pull request by davesmits**
An attempt to get #241 fixed

I noticed two faulty behaviors:
- the one described in the bug #241 
- When you add a new project in the filter bar; get those repositories; remove the proejct again. The repositories from the removed project stay visible

This change should reset the items in the state instead of just keep adding more and more

DISCLAIMER:
So far not been able to test it locally.. which makes it a bit of a risky change. Maybe a maintainer can give me a hand?

### CODE REVIEW

**Review by cribeiro84 — APPROVED** [review]

**Comment by cribeiro84** [comment]
@davesmits thanks for raising this PR, I will try to look into it in the following days. It's breaking the build due the invalid variable declaration.

**Review by cribeiro84 — CHANGES_REQUESTED** [review]
It's breaking the build, I will look into this in the following days

**Comment by davesmits** [comment]
I gave it another try but don't understand what is wrong and build results in missing file. So hope you want to help
image

**Comment by davesmits** [comment]
@cribeiro84 want to give it another look? should be building now again

**Comment by davesmits** [comment]
@cribeiro84 anything I can to do to get this merged or fixed?

**Comment by cribeiro84** [comment]
> @cribeiro84 anything I can to do to get this merged or fixed?

was this tested on your environment? Did you see any impact?

**Comment by davesmits** [comment]
I will give it a renew try this weekend. not sure where I left it off.

**Pull request closed without merging**
